# Generated by Django 4.2.5 on 2023-09-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.IntegerField(),
        ),
    ]
