# Generated by Django 4.2.5 on 2023-09-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazerapp', '0002_alter_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('preco', models.IntegerField()),
                ('imagem', models.FileField(upload_to='')),
                ('descricao', models.TextField(max_length=510)),
                ('categoria', models.TextField(max_length=61)),
            ],
        ),
    ]
