# Generated by Django 4.2.5 on 2023-09-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazerapp', '0003_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
