# Generated by Django 4.2.5 on 2023-09-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazerapp', '0007_alter_produto_categoria_alter_produto_descricao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Produtos',
        ),
    ]
