# Generated by Django 4.2.5 on 2023-09-18 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazerapp', '0010_alter_produtos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='tempo',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
