# Generated by Django 4.2.5 on 2023-09-18 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazerapp', '0011_produtos_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tempo',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(null=True, upload_to='../static/assets/images/%d/%m/%y'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(null=True, upload_to='../static/assets/images/%d/%m/%y'),
        ),
    ]
