# Generated by Django 4.2.5 on 2023-09-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazerapp', '0014_alter_produtos_imagem_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(null=True, upload_to='fotos/%d/%m/%y'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos/%d/%m/%y'),
        ),
    ]
