# Generated by Django 4.2.5 on 2023-09-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazerapp', '0015_alter_produtos_imagem_alter_usuario_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(upload_to='fotos/%d/%m/%y'),
        ),
    ]
