# Generated by Django 4.2.5 on 2023-09-19 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_password',
        ),
    ]
