# Generated by Django 4.2.5 on 2023-09-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_user_email_remove_usuario_user_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_username',
        ),
    ]
