# Generated by Django 4.2.5 on 2023-09-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='u_apelido',
            field=models.TextField(blank=True, max_length=126, null=True),
        ),
    ]
